name: Run License Tests
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  license_tests:
    uses: neongeckocom/.github/.github/workflows/license_tests.yml@master
    with:
      packages-exclude: '^(precise-runner|fann2|tqdm|bs4|ovos-phal-plugin|ovos-skill|neon-core|nvidia|neon-phal-plugin|bitstruct|audioread|RapidFuzz).*'
